spring:
  application:
    name: inventoryservice
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing
    username: root
    password: password


  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080


#OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs


